### ISSUE TITLE
[Bug]: using Langfuse integration via litellm proxy

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1026]
### What happened?

bug using Langfuse integration via litellm proxy

### Relevant log output

```shell
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/nix/store/z7yziam4nyg7xy5gp9r6wadzf5krqm8i-python3-3.10.12/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Users/danieljacobs/Library/Caches/pypoetry/virtualenvs/llmproxy-xHaVGnjY-py3.10/lib/python3.10/site-packages/langfuse/task_manager.py", line 86, in run
    self.upload()
  File "/Users/danieljacobs/Library/Caches/pypoetry/virtualenvs/llmproxy-xHaVGnjY-py3.10/lib/python3.10/site-packages/langfuse/task_manager.py", line 91, in upload
    batch = self._next()
  File "/Users/danieljacobs/Library/Caches/pypoetry/virtualenvs/llmproxy-xHaVGnjY-py3.10/lib/python3.10/site-packages/langfuse/task_manager.py", line 69, in _next
    item_size = len(json.dumps(item, cls=DatetimeSerializer).encode())
  File "/nix/store/z7yziam4nyg7xy5gp9r6wadzf5krqm8i-python3-3.10.12/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/nix/store/z7yziam4nyg7xy5gp9r6wadzf5krqm8i-python3-3.10.12/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/nix/store/z7yziam4nyg7xy5gp9r6wadzf5krqm8i-python3-3.10.12/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/danieljacobs/Library/Caches/pypoetry/virtualenvs/llmproxy-xHaVGnjY-py3.10/lib/python3.10/site-packages/langfuse/serializer.py", line 14, in default
    return json.JSONEncoder.default(self, obj)
  File "/nix/store/z7yziam4nyg7xy5gp9r6wadzf5krqm8i-python3-3.10.12/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Headers is not JSON serializable
```

**Comment by ghost** [comment]
potential fix (user submitted) 

```python
            ig = InitialGeneration(...)
            if ig.metadata['headers']:
                headers = ig.metadata['headers']
                ig.metadata['headers'] = [(k.decode("utf-8"), v.decode("utf-8")) for (k,v) in headers.raw]
```

**Comment by ghost** [comment]
working on this now. Able to repro this bug.

**Comment by ghost** [comment]
fix pushed - https://github.com/BerriAI/litellm/commit/58848841e1884b1911daca8a772288ebde71edc9

**Comment by ghost** [comment]
cc: @kloudtaxi

I don't think our langfuse testing is great though. If you'd like to contribute better testing here, we'd really appreciate it - https://github.com/BerriAI/litellm/blob/main/litellm/tests/test_langfuse.py

**Comment by ghost** [comment]
also added a new test for langfuse + proxy - https://github.com/BerriAI/litellm/commit/d2de7ffe278841c2146f8099945bf40812e20d1d

**Comment by kloudtaxi** [comment]
@krrishdholakia just a FYI, while testing against the hosted version of Langfuse from US, I noticed that you have to explicitly specify `LANGFUSE_HOST='https://us.cloud.langfuse.com'` (notice the 'us' subdomain) otherwise LiteLLM call to Langfuse fails after 3 tries.

**Comment by CalabiYau14** [comment]
Hi @krrishdholakia! I still get the same error when using the langfuse + proxy. I tried the latest version on pypi (v.1.12.0) and the master branch :-(. Thanks in advance and cheers!

**Comment by CalabiYau14** [comment]
Seems to only show up when using streaming mode, e.g. in openAIClient with stream=True
