### ISSUE TITLE
Railway deployment failed - no idea why

### ISSUE THREAD

**Issue by agileben** [BerriAI/litellm#5712]
✔ Generated Prisma Client Python (v0.11.0) to ./../../prisma in 335ms

 

INFO:     Started server process [1]

INFO:     Waiting for application startup.

ERROR:    Traceback (most recent call last):

  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 732, in lifespan

    async with self.lifespan_context(app) as maybe_state:

  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 608, in __aenter__

    await self._router.startup()

  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 709, in startup

    await handler()

  File "/usr/local/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 2905, in startup_event

    create_view_response = await prisma_client.check_view_exists()

                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/backoff/_async.py", line 151, in retry

    ret = await target(*args, **kwargs)

          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/litellm/proxy/utils.py", line 995, in check_view_exists

    if required_view not in ret[0]["view_names"]:

       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

TypeError: argument of type 'NoneType' is not iterable

 

ERROR:    Application startup failed. Exiting.

**Comment by ghost** [comment]
Hey @agileben this issue is fixed here - https://github.com/BerriAI/litellm/pull/5723

I'm assuming this is a new db with no existing views. It relates to a recent change made (v1.44.28+) which moved the view creation logic out of the proxy startup.

**Comment by lackeyi** [comment]
Is there a workaround for this? I am trying to get an instance running in Azure, and it looks like this may be the issue I am running into as well.

**Comment by ghost** [comment]
It'll be out by eod. if it's urgent use v1.44.27

**Comment by lackeyi** [comment]
That is impressive turn around! Thanks for the quick response!

**Comment by lackeyi** [comment]
I have tried rolling back to 1.44.27 and also tried the new 1.46.1 this morning. I am still seeing this same issue.

**Comment by ishaan-jaff** [comment]
fixed here: https://github.com/BerriAI/litellm/pull/5740 

we needed a check for if the ret value is None

**Comment by lackeyi** [comment]
I was able to get it to run on v1.44.17-stable as a temporary workaround.
